/* Встреча у двери (minigames/smalltalk.js): кто что говорит. Правила словами — docs/ORDERS.md «Разговор с клиентом».
   Тон — «No, I'm Not a Human»: странные, мрачноватые, гипертрофированные люди, недосказанность, бытовой абсурд,
   сатира на поступки (ставки, водка, мент берёт, лицемеры, одиночество). Шутим над поступком и ситуацией —
   не над национальностью, ориентацией, полом, инвалидностью как таковой. Мат, секс, выпивка, ставки — только adult.

   Кто (ключи WHO — те же имена, что у героев трека 10; катсцены в городе — encounters.js — берут тексты отсюда):
     angry_granny kind_granny snitch_granny kind_oldman_cat lonely_oldman bettor alcoholic_onearm hikan corrupt_cop gopnik
     dandy_coffee alien shy_burger bandit90s taxi oppositionist oppositionist_wife massage prostitute twofaced_patriot
     zozh_blogger kind_auntie happy_dad fake_nice tired_mom henpecked sweatsuit_noleg student drunk_neighbor conspiracist
     blogger fisher jock car_guy normis

   Встреча (единый формат): { id, who, adult?, emo, say, a, b, kids? }
     who   — кто это (ключ WHO ниже): внешность портрета, пол (глаголы в роде), подсказка для 3D-сцены подъезда;
     emo   — лицо, пока говорит (people.js MOOD_FACE: happy angry sad scared surprised ok);
     say   — его реплика: одна-две короткие фразы, до ~80 букв;
     a, b  — два ответа курьера (сверху вниз): { me, re, mood, out, row?, slam?, bonus? }
       me   — что говорит курьер: 1—4 слова;
       re   — короткая реакция человека ('' — молча); slam — после неё хлопает дверью;
       mood — лицо на реакции и на мини-карточке оплаты;
       out  — итог (деньгами): 'tip' чаевые +15 % цены адреса и респект · 'big' +30 % · 'cut' чаевые −50 % ·
              'none' без чаевых · '0' ничего (числа — econ.js TALK);
       row  — смешная строка итога в чеке («послал бабушку»); нет — обычная по out;
       bonus — 'find' (подсказка, где находка) или 'zhenya' (скидка у Дяди Жени);
     adult — только во взрослой версии;
     kids  — в детской заменить поля: { say?, a?: {…}, b?: {…} } (мягкий вариант той же встречи).
   Строки игрока — ключи перевода (N_), ru здесь, en — src/i18n/en.json. WHO — не для игрока, не переводится. */
const N_ = s => s;

/* Кто стоит за дверью. name — тип человека словами; look — поправки к портрету (people.js makeLook: age, hair, hairC,
   beard, head, headC, glasses, eyes, brows, mouth, skin, lip, fat/shape…), портрет клиента «переодевается» под роль;
   fem — пол (нет — кто угодно); home — какая за дверью квартира (для 3D-сцены встречи, src/uilab / people.js). */
export const WHO = {
  normis:   { name: 'обычный человек', home: 'обычная хрущёвка: ковёр на стене, телевизор' },
  angry_granny:    { name: 'злая бабка', fem: true, home: 'иконы, банки с огурцами, телевизор орёт, кот смотрит',
              look: { age: 'old', wrinkles: true, hairC: '#d4d0ca', hair: 'bun', head: 'bandana', headC: '#6b2e4a', glasses: 'none', brows: 'angry', mouth: 'frown' } },
  kind_granny:   { name: 'добрая бабушка', fem: true, home: 'пирожки, фотографии внуков, сервант с хрусталём',
              look: { age: 'old', wrinkles: true, hairC: '#d4d0ca', hair: 'bun', head: 'none', glasses: 'round', mouth: 'smile' } },
  snitch_granny:   { name: 'соседка-стукачка', fem: true, home: 'у двери стул и бинокль, на стене график «кто когда пришёл»',
              look: { age: 'old', wrinkles: true, hairC: '#9a948c', hair: 'bob', glasses: 'square', brows: 'raised', mouth: 'small' } },
  kind_oldman_cat: { name: 'добрый дед с котом', fem: false, home: 'кот Барсик на всех стульях, миски, коврики, фото кота на стене',
              look: { age: 'old', wrinkles: true, hair: 'receding', hairC: '#b8b2aa', beard: 'full', glasses: 'round', mouth: 'smile' } },
  lonely_oldman:     { name: 'одинокий дед', fem: false, home: 'чисто, пусто, один стул, радио, фото жены',
              look: { age: 'old', wrinkles: true, hair: 'receding', hairC: '#d4d0ca', beard: 'mustache', head: 'none' } },
  bettor:   { name: 'злобный ставочник', fem: false, home: 'три телефона, футбол на всех экранах, коробки из-под лапши',
              look: { beard: 'stubble', stubble: true, head: 'cap', headC: '#2b2a30', brows: 'angry', eyes: 'sleepy' } },
  alcoholic_onearm:   { name: 'однорукий алкаш', fem: false, home: 'бутылки рядами, табуретка, часы стоят',
              look: { beard: 'stubble', stubble: true, head: 'beanie', headC: '#3b4a5a', eyes: 'sleepy', mouth: 'smirk' } },
  hikan:    { name: 'хикан в капюшоне', fem: false, home: 'темно, монитор, энергетики, турник в проёме',
              look: { age: 'young', head: 'hood', headC: '#2b2a30', eyes: 'narrow', mouth: 'line' } },
  corrupt_cop:      { name: 'продажный мент', fem: false, home: 'новая плазма, коробки с техникой, фуражка на гвозде',
              look: { head: 'cap', headC: '#3b4a5a', beard: 'mustache', fat: true, shape: 'chubby', mouth: 'smirk' } },
  gopnik:   { name: 'гопник', fem: false, home: 'шелуха от семечек, ковёр, спортивки сушатся',
              look: { age: 'young', hair: 'buzz', head: 'cap', headC: '#2b2a30', brows: 'angry', eyes: 'narrow' } },
  dandy_coffee:  { name: 'усатый модник с кофе', fem: false, home: 'кирпич, лампочки Эдисона, пластинки, кофемашина за 300 тысяч',
              look: { age: 'young', beard: 'mustache', glasses: 'round', head: 'beanie', headC: '#e08a4f', hair: 'side' } },
  alien:    { name: 'инопланетянин', home: 'фольга на окнах, мигает что-то под простынёй, пахнет озоном',
              look: { skin: '#9fd47a', hair: 'bald', head: 'none', beard: 'none', eyes: 'white', glasses: 'none', brows: 'raised' } },
  shy_burger:   { name: 'стеснительный бургер (в маскировке: шляпа и тёмные очки)', home: 'шторы задёрнуты, на полу листовки «Бургер-Кинг всегда прав»',
              look: { head: 'hat', headC: '#8a7a5a', glasses: 'sun', glassC: '#1d1a1f', beard: 'none', mouth: 'small' } },
  bandit90s:   { name: 'бандит из 90-х', fem: false, home: 'кожаный диван, малиновый пиджак в рамке, сейф, цепь на гвозде',
              look: { hair: 'buzz', head: 'none', fat: true, shape: 'chubby', glasses: 'sun', beard: 'none', mouth: 'smirk' } },
  taxi:     { name: 'таксист', fem: false, home: 'шашечки на холодильнике, освежитель-ёлочка, чётки',
              look: { head: 'cap', headC: '#e0b13f', beard: 'mustache', fat: true, shape: 'chubby' } },
  oppositionist:     { name: 'оппозиционер (потом его арестуют)', fem: false, home: 'листовки, коробки, на стене карта города с забором красным',
              look: { age: 'young', glasses: 'square', beard: 'goatee', hair: 'curly' } },
  oppositionist_wife: { name: 'жена оппозиционера', fem: true, home: 'вещи разбросаны после обыска, его куртка на вешалке',
              look: { eyes: 'sleepy', mouth: 'line', hair: 'ponytail' } },
  massage:  { name: 'работница массажного салона «с хэппи-эндом»', fem: true, home: 'розовый свет, кушетка, благовония, табличка «Нефрит»',
              look: { lip: '#c23a4a', hair: 'long', blush: true, eyes: 'lashes' } },
  prostitute:    { name: 'ночная бабочка', fem: true, home: 'зеркало в лампочках, туфли горой, тетрадка с расходами',
              look: { lip: '#8a2a3a', hair: 'long', eyes: 'lashes', brows: 'arched' } },
  twofaced_patriot: { name: 'чиновник-лицемер', fem: false, home: 'портрет начальства, плакат «Здоровый город», коробки пиццы стопкой',
              look: { hair: 'side', fat: true, shape: 'chubby', glasses: 'square', beard: 'none', top: 'jacket' } },
  zozh_blogger:     { name: 'ЗОЖ-блогер', home: 'кольцевая лампа, гантели, шпинат на камеру — и коробки пиццы за кадром',
              look: { age: 'young', head: 'headband', headC: '#59b06a', mouth: 'smile' } },
  kind_auntie:     { name: 'добрая тётя', fem: true, home: 'тепло, пахнет борщом, полотенца, кот на батарее',
              look: { mouth: 'smile', blush: true, hair: 'curly' } },
  happy_dad:      { name: 'позитивный мужик', fem: false, home: 'дети бегают, шарики, торт, всем весело',
              look: { mouth: 'smile', beard: 'full' } },
  fake_nice:     { name: 'притворщица (улыбается, а чаевых нет)', fem: true, home: 'дорогой ремонт, табличка «Живи. Люби. Смейся»',
              look: { mouth: 'smile', lip: '#d9608a', glasses: 'sun' } },
  tired_mom:      { name: 'мать троих детей', fem: true, home: 'игрушки везде, кто-то орёт, на плите пригорает',
              look: { eyes: 'sleepy', hair: 'ponytail', mouth: 'line' } },
  henpecked:  { name: 'муж, который прячется от жены', fem: false, home: 'гараж вместо квартиры: жена думает, что он там пьёт',
              look: { hair: 'receding', beard: 'stubble', stubble: true, brows: 'sad' } },
  sweatsuit_noleg:  { name: 'ветеран бургерной войны (свошник, в коляске)', fem: false, home: 'медали на ковре, коляска, пандуса нет',
              look: { hair: 'buzz', beard: 'stubble', stubble: true, brows: 'sad', head: 'none' } },
  student:  { name: 'студент', home: 'матрас на полу, лапша, конспекты',
              look: { age: 'young', glasses: 'round', mouth: 'small' } },
  drunk_neighbor:    { name: 'пьяный сосед', fem: false, home: 'праздник третий день, гармонь, салат на полу',
              look: { eyes: 'sleepy', blush: true, beard: 'stubble', stubble: true } },
  conspiracist:    { name: 'странный тип (заговоры)', home: 'фольга на окнах, газеты пачками, карта с булавками',
              look: { eyes: 'white', glasses: 'none', head: 'beanie', headC: '#b8b2aa' } },
  blogger:  { name: 'блогер', home: 'кольцевая лампа, телефон на палке',
              look: { age: 'young' } },
  fisher:   { name: 'рыбак', fem: false, home: 'удочки в коридоре, ведро, запах реки',
              look: { head: 'hat', headC: '#3f5a3a', beard: 'full' } },
  jock:     { name: 'качок', fem: false, home: 'гантели, протеин, зеркало во всю стену',
              look: { age: 'young', hair: 'buzz', beard: 'none' } },
  car_guy:      { name: 'мужик с машиной', fem: false, home: 'запчасти на балконе, карбюратор на кухне',
              look: { beard: 'mustache', head: 'cap', headC: '#2e4a6b' } },
};

export const SITS = [
  /* ── обычные люди: город, быт ── */
  { id: 'pothole', who: 'normis', emo: 'angry',
    say: N_('Видел яму на проспекте? Там мой «Жигуль». Третий год.'),
    a: { me: N_('Соболезную'), re: N_('Спасибо. Ты первый, кто сказал.'), mood: 'sad', out: 'tip' },
    b: { me: N_('Хорошая яма'), re: N_('…Хорошая. Глубокая. Иди.'), mood: 'angry', out: 'cut' } },
  { id: 'drill', who: 'normis', emo: 'angry',
    say: N_('Сосед сверлит седьмой год. По-моему, он роет отсюда.'),
    a: { me: N_('Пусть роет'), re: N_('И ты с ним заодно.'), mood: 'angry', out: 'cut', slam: true },
    b: { me: N_('Я бы тоже рыл'), re: N_('…Да. Отсюда — только вниз.'), mood: 'sad', out: 'tip' } },
  { id: 'rain', who: 'normis', emo: 'sad',
    say: N_('Как закажу пиццу — дождь. Это ты его возишь?'),
    a: { me: N_('Да'), re: N_('Я так и думаю. Спасибо, что честно.'), mood: 'sad', out: 'tip' },
    b: { me: N_('Нет'), re: N_('Все так говорят.'), mood: 'angry', out: '0', slam: true } },
  { id: 'ex', who: 'normis', emo: 'sad', fem: true,
    say: N_('Бывший пишет. Отвечать?'),
    a: { me: N_('Нет'), re: N_('Правильно. Пицца не изменяет.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Да'), re: N_('Ответила. Он прислал «ок». Спасибо, блин.'), mood: 'angry', out: 'cut', row: N_('плохой совет') } },
  { id: 'newbie', who: 'normis', emo: 'surprised',
    say: N_('Я тут неделю. Правда, что отсюда не выпускают?'),
    a: { me: N_('Правда'), re: N_('Ясно. Тогда две пиццы. В следующий раз.'), mood: 'sad', out: 'tip' },
    b: { me: N_('Слухи'), re: N_('Тогда почему ты шёпотом?'), mood: 'scared', out: '0' } },
  { id: 'catlegend', who: 'normis', emo: 'scared',
    say: N_('Кот у промзоны правда размером с «Волгу»?'),
    a: { me: N_('С «Ниву»'), re: N_('Растёт. Там ещё блестит что-то. Глянь.'), mood: 'scared', out: 'tip', bonus: 'find' },
    b: { me: N_('Сказки'), re: N_('Сосед тоже так говорил. Сосед.'), mood: 'scared', out: '0', slam: true } },
  { id: 'bus', who: 'normis', emo: 'sad',
    say: N_('Пятый автобус ходит? Жду с утра. Со вчерашнего.'),
    a: { me: N_('Ходит'), re: N_('Спасибо. Подожду ещё.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Отменили'), re: N_('Я знаю. Я просто жду.'), mood: 'sad', out: '0' } },
  { id: 'queue', who: 'normis', emo: 'ok',
    say: N_('Очередь на КПП большая? Брат с большой земли едет.'),
    a: { me: N_('До горизонта'), re: N_('Значит, к Новому году. Слушай, тут одна штука лежит…'), mood: 'ok', out: 'tip', bonus: 'find' },
    b: { me: N_('Очереди нет'), re: N_('…Значит, его не пустили.'), mood: 'sad', out: '0' } },
  { id: 'car', who: 'car_guy', emo: 'happy',
    say: N_('Видал ласточку у подъезда? Сам перебрал! Каждый болтик!'),
    a: { me: N_('Ту, на кирпичах?'), re: N_('Колёса — летом. Иди уже.'), mood: 'angry', out: 'cut' },
    b: { me: N_('Огонь машина'), re: N_('Свой! Скажи Дяде Жене, что ты от меня.'), mood: 'happy', out: 'tip', bonus: 'zhenya' } },
  { id: 'grandson', who: 'kind_granny', emo: 'happy',
    say: N_('Внук в Москве программист! Сайты делает!'),
    a: { me: N_('Звонит?'), re: N_('…На Новый год. Иногда.'), mood: 'sad', out: '0' },
    b: { me: N_('Молодец внук'), re: N_('Весь в меня! На, на чай. Не спорь.'), mood: 'happy', out: 'tip' } },
  { id: 'fish', who: 'fisher', emo: 'happy',
    say: N_('Щуку вчера взял — метр двадцать! Ну, восемьдесят.'),
    a: { me: N_('Сорок?'), re: N_('…Тридцать. Но злая была.'), mood: 'sad', out: '0' },
    b: { me: N_('Ого'), re: N_('Вот! Хоть кто-то верит. Держи.'), mood: 'happy', out: 'tip' } },
  { id: 'gym', who: 'jock', emo: 'happy',
    say: N_('Смотри бицуху! Коробку одной рукой держу.'),
    a: { me: N_('Мощь'), re: N_('Я Дяде Жене движки таскаю. Скажи, что от меня.'), mood: 'happy', out: 'tip', bonus: 'zhenya' },
    b: { me: N_('Она пустая'), re: N_('…Не пустая. Там душа.'), mood: 'sad', out: 'cut' } },
  { id: 'million', who: 'normis', emo: 'ok', fem: false,
    say: N_('Сдачи не надо. Рассказать, как я заработал первый миллион?'),
    a: { me: N_('Давайте'), re: N_('Продал тёщин гараж, пока она была на даче. Тс-с.'), mood: 'happy', out: 'big', row: N_('секрет миллиона') },
    b: { me: N_('Не надо'), re: N_('Правильно. Меньше знаешь — крепче спишь.'), mood: 'ok', out: '0' } },
  { id: 'slice', who: 'normis', emo: 'ok',
    say: N_('Если этот кусок не съем — скидку дашь?'),
    a: { me: N_('Нет'), re: N_('Тогда съем назло.'), mood: 'angry', out: '0' },
    b: { me: N_('Дам'), re: N_('Врёшь. Но приятно.'), mood: 'happy', out: 'tip' } },
  { id: 'piggy', who: 'normis', emo: 'sad',
    say: N_('Можно мелочью? Сейчас свинью разобью…'),
    a: { me: N_('Бейте'), re: N_('Хрясь. Ровно на пиццу. Свиньи больше нет.'), mood: 'sad', out: 'none', row: N_('разбили свинью') },
    b: { me: N_('Жалко свинью'), re: N_('…Ладно. Переводом. Живи, свинья.'), mood: 'happy', out: 'tip' } },
  { id: 'pickles', who: 'kind_granny', emo: 'happy',
    say: N_('Давай на огурцы? Свои, хрустящие. Банка — пицца.'),
    a: { me: N_('Давайте'), re: N_('Хороший ты. Огурчик на дорожку.'), mood: 'happy', out: 'tip', row: N_('банка огурцов') },
    b: { me: N_('Деньгами'), re: N_('Деньги… Все хотят деньги.'), mood: 'sad', out: 'cut' } },
  { id: 'dog', who: 'normis', emo: 'happy',
    say: N_('Угадаешь, как зовут собаку, — дам на чай.'),
    a: { me: N_('Граф?'), re: N_('ГРАФ. Как?!'), mood: 'surprised', out: 'big', row: N_('угадал собаку') },
    b: { me: N_('Пицца?'), re: N_('Нет. Но теперь — Пицца.'), mood: 'happy', out: 'tip' } },
  { id: 'selfie', who: 'blogger', emo: 'happy',
    say: N_('Можно с тобой сфоткаться? Подписчики обожают курьеров.'),
    a: { me: N_('Можно'), re: N_('Подпишу: «мой курьер». Мой.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Нельзя'), re: N_('Поздно. Уже сфоткано.'), mood: 'happy', out: '0' } },
  { id: 'mom', who: 'normis', emo: 'happy',
    say: N_('Сфоткай меня у подъезда? Маме покажу, что я не в тайге.'),
    a: { me: N_('Улыбочку'), re: N_('Хорошо вышло. Забора почти не видно.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Тут тайга'), re: N_('Не говори маме.'), mood: 'scared', out: '0' } },
  { id: 'stream', who: 'blogger', emo: 'happy',
    say: N_('Мы в эфире! Скажи что-нибудь подписчикам!'),
    a: { me: N_('Привет'), re: N_('Чат пишет: «скучно». Спасибо.'), mood: 'sad', out: '0' },
    b: { me: N_('Помогите'), re: N_('Ха! Донат пришёл! Держи!'), mood: 'happy', out: 'big', row: N_('донат от чата') } },
  { id: 'granny', who: 'kind_granny', emo: 'happy',
    say: N_('Сынок, зайди на чай. Пирожки, альбом за пятьдесят лет.'),
    a: { me: N_('Зайду'), re: N_('Врёшь. Но пирожок держи.'), mood: 'happy', out: 'tip', row: N_('пирожок с капустой') },
    b: { me: N_('Некогда'), re: N_('Всем некогда.'), mood: 'sad', out: '0', slam: true } },
  { id: 'chess', who: 'lonely_oldman', emo: 'ok',
    say: N_('Партейку в шахматы? Быстро, минут на сорок.'),
    a: { me: N_('Е2—е4'), re: N_('Сильно. Ничья. Иди.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Я в шашки'), re: N_('Шашки — для слабых. Свободен.'), mood: 'angry', out: 'cut', slam: true } },
  { id: 'antenna', who: 'conspiracist', emo: 'scared',
    say: N_('Коробка квадратная, чтобы за нами следить. Ты знал?'),
    a: { me: N_('Знал'), re: N_('Тс-с. Ты свой. Коробку я сожгу.'), mood: 'scared', out: 'tip' },
    b: { me: N_('Это коробка'), re: N_('Так они и говорят.'), mood: 'scared', out: '0', slam: true } },
  { id: 'son', who: 'normis', emo: 'surprised',
    say: N_('Сын спрашивает: пицца круглая, коробка квадратная. Почему?'),
    a: { me: N_('Так дешевле'), re: N_('Так и скажу. Он уже большой.'), mood: 'ok', out: 'tip' },
    b: { me: N_('Это тайна'), re: N_('Теперь он хочет в курьеры. Спасибо.'), mood: 'sad', out: '0' } },
  { id: 'barsik', who: 'kind_oldman_cat', emo: 'scared',
    say: N_('Тс-с! Барсик спит. Проснётся — кусает курьеров.'),
    a: { me: N_('(шёпотом) Понял'), re: N_('(шёпотом) Хороший. На, за тишину.'), mood: 'happy', out: 'tip' },
    b: { me: N_('МЯУ!'), re: N_('…Беги.'), mood: 'scared', out: '0', slam: true, row: N_('разбудил Барсика') } },

  /* ── злые и тяжёлые ── */
  { id: 'babka', who: 'angry_granny', emo: 'angry',
    say: N_('Опять ты. Дверью не хлопай, наркоман.'),
    kids: { say: N_('Опять ты. Дверью не хлопай, хулиган.') },
    a: { me: N_('Я не хлопал'), re: N_('Ещё похлопаешь.'), mood: 'angry', out: '0', slam: true },
    b: { me: N_('Сами вы'), re: N_('Милицию вызову. Спасибо за пиццу.'), mood: 'angry', out: 'cut' } },
  { id: 'babkasex', who: 'angry_granny', emo: 'happy', adult: true,
    say: N_('Внучек, зайди. Я в халатике. Деда нет с восемьдесят девятого.'),
    a: { me: N_('Иди нахер, старая'), re: N_('Хамло! Чтоб у тебя колесо отвалилось.'), mood: 'angry', out: 'none', row: N_('послал бабушку') },
    b: { me: N_('У меня смена'), re: N_('Смена у него… Все вы со сменой.'), mood: 'sad', out: '0' } },
  { id: 'snitch', who: 'snitch_granny', emo: 'ok',
    say: N_('Запиши: в сорок третьей опять гости. Я всё пишу.'),
    a: { me: N_('Записал'), re: N_('Молодец. Тебя я тоже записала.'), mood: 'happy', out: '0', row: N_('тебя записали') },
    b: { me: N_('Не буду'), re: N_('Записала.'), mood: 'angry', out: 'cut', slam: true } },
  { id: 'bettor', who: 'bettor', emo: 'angry', adult: true,
    say: N_('Я поставил, что ты опоздаешь. Ты что наделал?'),
    a: { me: N_('Простите'), re: N_('Простите… Минус сорок тысяч. Простите.'), mood: 'angry', out: 'none', slam: true, row: N_('сорвал ставку') },
    b: { me: N_('Ставь на меня'), re: N_('…А ведь мысль. На, на удачу.'), mood: 'surprised', out: 'tip' } },
  { id: 'onearm', who: 'alcoholic_onearm', emo: 'ok', adult: true,
    say: N_('Положи на коврик. Рука занята.'),
    a: { me: N_('Поставь бутылку'), re: N_('Ты чё. Это последнее, что у меня есть.'), mood: 'angry', out: '0', slam: true },
    b: { me: N_('Ладно'), re: N_('Человек! Дал бы пять, но — сам видишь.'), mood: 'happy', out: 'tip' } },
  { id: 'hikan', who: 'hikan', emo: 'angry',
    say: N_('Э. Пицца без ананасов? Если с ананасами — ты попал.'),
    a: { me: N_('Без'), re: N_('Норм. Ты норм.'), mood: 'ok', out: 'tip' },
    b: { me: N_('Не смотрел'), re: N_('…Повезло тебе. Без.'), mood: 'angry', out: '0', slam: true } },
  { id: 'copslice', who: 'corrupt_cop', emo: 'ok',
    say: N_('Так. Пицца без чека — это статья. Кусок — на экспертизу.'),
    a: { me: N_('Берите'), re: N_('Экспертиза покажет, что вкусно. Свободен.'), mood: 'happy', out: 'cut', row: N_('кусок на экспертизу') },
    b: { me: N_('Вот чек'), re: N_('Чек… Умные все стали.'), mood: 'angry', out: '0', slam: true } },
  { id: 'copfine', who: 'corrupt_cop', emo: 'ok',
    say: N_('Ты сегодня нарушал? Все нарушали. Тыща — и не нарушал.'),
    a: { me: N_('Не нарушал'), re: N_('Тогда две.'), mood: 'happy', out: 'none', row: N_('откупился от мента') },
    b: { me: N_('Нарушал'), re: N_('Честный. Это хуже. Иди.'), mood: 'surprised', out: '0' } },
  { id: 'gopnik', who: 'gopnik', emo: 'angry',
    say: N_('Слышь. А чё пицца круглая? Ты чё, умный?'),
    a: { me: N_('Нет'), re: N_('Вот. Живи.'), mood: 'ok', out: '0' },
    b: { me: N_('Да'), re: N_('…Уважаю. Умных мало.'), mood: 'surprised', out: 'tip' } },
  { id: 'seeds', who: 'gopnik', emo: 'ok',
    say: N_('Семки есть? А мелочь? А если найду?'),
    a: { me: N_('Нету'), re: N_('Мда. Тяжело тебе, братан.'), mood: 'sad', out: '0' },
    b: { me: N_('Есть пицца'), re: N_('Пицца… Это уважительно.'), mood: 'happy', out: 'tip' } },
  { id: 'bandit', who: 'bandit90s', emo: 'ok',
    say: N_('Пацан, ты от кого? Кто район держит?'),
    a: { me: N_('Я от пиццы'), re: N_('От пиццы… Уважаемая контора.'), mood: 'ok', out: 'tip' },
    b: { me: N_('Никто'), re: N_('Теперь я держу. С тебя — за район.'), mood: 'happy', out: 'none', row: N_('отдал «за район»') } },
  { id: 'veteran', who: 'sweatsuit_noleg', emo: 'sad',
    say: N_('Я с бургерной войны. Льготу обещали — скидку на пиццу. Где она?'),
    a: { me: N_('Не знаю'), re: N_('Никто не знает. Ладно. Держи.'), mood: 'sad', out: 'tip' },
    b: { me: N_('Спросите Толика'), re: N_('Спрашивал. Он сказал — спроси курьера.'), mood: 'angry', out: '0' } },
  { id: 'oppo', who: 'oppositionist', emo: 'ok',
    say: N_('Подпиши петицию против забора. Не посадят. Почти.'),
    a: { me: N_('Подпишу'), re: N_('Спасибо. Запомни моё лицо. Пригодится.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Мне нельзя'), re: N_('Всем нельзя. Поэтому и забор.'), mood: 'sad', out: '0' } },
  { id: 'oppowife', who: 'oppositionist_wife', emo: 'sad',
    say: N_('Его вчера забрали. Пицца на его имя. Возьмёте обратно?'),
    a: { me: N_('Оставьте себе'), re: N_('Спасибо. Вот, его чаевые. Он всегда давал.'), mood: 'sad', out: 'tip' },
    b: { me: N_('За что забрали?'), re: N_('Тс-с. Ни за что. Как всех.'), mood: 'scared', out: '0', slam: true } },
  { id: 'deda', who: 'lonely_oldman', emo: 'sad',
    say: N_('Поговори со мной минутку. Про что угодно.'),
    a: { me: N_('Погода хорошая'), re: N_('Хорошая… Спасибо. Это было хорошо.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Мне пора'), re: N_('Конечно. Всем пора.'), mood: 'sad', out: '0', slam: true } },
  { id: 'mom3', who: 'tired_mom', emo: 'sad',
    say: N_('Трое детей, муж на вахте. Ты первый взрослый за неделю.'),
    a: { me: N_('Держитесь'), re: N_('Держусь. Постой ещё секунду, а?'), mood: 'sad', out: 'tip' },
    b: { me: N_('Мне пора'), re: N_('Мне тоже. Куда-нибудь.'), mood: 'sad', out: '0', slam: true } },
  { id: 'vodka', who: 'henpecked', emo: 'scared', adult: true,
    say: N_('Не говори жене про пиццу. Она думает, я водку пью.'),
    a: { me: N_('Могила'), re: N_('Пусть думает. Так ей спокойнее.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Скажу'), re: N_('Скажи, что водку. Умоляю.'), mood: 'scared', out: 'cut' } },
  { id: 'drunk', who: 'drunk_neighbor', emo: 'happy', adult: true,
    say: N_('Братан! Выпьем за пиццу! За круглую!'),
    a: { me: N_('Я за рулём'), re: N_('А я за всех. За тебя!'), mood: 'happy', out: 'tip' },
    b: { me: N_('Наливай'), re: N_('Нету. Выпил. Иди.'), mood: 'sad', out: '0', slam: true } },
  { id: 'inlaw', who: 'henpecked', emo: 'scared', adult: true,
    say: N_('Слышь, зайди, а? Тёща приехала. Одному — пиздец.'),
    a: { me: N_('Держитесь'), re: N_('Держусь. Девятый день.'), mood: 'sad', out: 'tip' },
    b: { me: N_('Удачи'), re: N_('Предатель.'), mood: 'angry', out: 'cut', slam: true } },
  { id: 'burgers', who: 'normis', emo: 'angry', adult: true,
    say: N_('Бургеры под окнами орут. Сбивай их, бля, я разрешаю!'),
    a: { me: N_('Сбиваю'), re: N_('Красавчик. Это от всего подъезда.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Они тоже люди'), re: N_('Они бургеры!'), mood: 'angry', out: '0', slam: true } },
  { id: 'massage', who: 'massage', emo: 'happy', adult: true,
    say: N_('Массаж с хэппи-эндом. Курьерам скидка.'),
    a: { me: N_('У меня смена'), re: N_('У всех смена. Ладно, остывай.'), mood: 'ok', out: '0' },
    b: { me: N_('Какой хэппи-энд?'), re: N_('Пиццу вместе съедим. Шутка. Иди.'), mood: 'happy', out: 'tip' } },
  { id: 'night', who: 'prostitute', emo: 'ok', adult: true,
    say: N_('О, еда. Первый за ночь, кто пришёл с едой.'),
    a: { me: N_('Тяжёлая ночь?'), re: N_('Как у всех. Только платят сразу.'), mood: 'ok', out: 'tip' },
    b: { me: N_('Приятного'), re: N_('Вежливый. Подозрительно.'), mood: 'surprised', out: '0' } },

  /* ── притворщики и лицемеры ── */
  { id: 'official', who: 'twofaced_patriot', emo: 'ok',
    say: N_('Администрация — против вредной еды. Это четыре пиццы на совещание.'),
    a: { me: N_('Приятного'), re: N_('Это не мне. Это народу. Народ — я.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Вредно же'), re: N_('Вредно такое говорить. Фамилия?'), mood: 'angry', out: 'cut', slam: true, row: N_('попал в список') } },
  { id: 'zozh', who: 'zozh_blogger', emo: 'scared',
    say: N_('Это не мне. Это… соседу. Никому, ладно?'),
    a: { me: N_('Конечно, соседу'), re: N_('Да. Соседу. Ему четыре сыра.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Спалился'), re: N_('Двадцать тысяч подписчиков. Молчи. На.'), mood: 'scared', out: 'big', row: N_('за молчание') } },
  { id: 'fake', who: 'fake_nice', emo: 'happy',
    say: N_('Ой, какой молодец! Чаевые… ой, карта не проходит. Ну ты понял.'),
    a: { me: N_('Понял'), re: N_('Ты чудо! Пять звёзд. Наверное.'), mood: 'happy', out: 'none', row: N_('чаевые «потом»') },
    b: { me: N_('Наличными?'), re: N_('…Хамло. На свои копейки.'), mood: 'angry', out: '0', slam: true } },
  { id: 'burger', who: 'shy_burger', emo: 'scared',
    say: N_('Я не бургер. Я человек. Просто люблю пиццу. Никому.'),
    a: { me: N_('Никому'), re: N_('Спасибо. И не сбивай нас, ладно?'), mood: 'happy', out: 'tip' },
    b: { me: N_('Ты бургер'), re: N_('Тише! На, держи. За молчание.'), mood: 'scared', out: 'big', row: N_('бургер откупился') } },
  { id: 'hipster', who: 'dandy_coffee', emo: 'ok',
    say: N_('Открываю кофейню. Пятую на этой улице. Придёшь?'),
    a: { me: N_('Приду'), re: N_('Не придёшь. Никто не приходит.'), mood: 'sad', out: '0' },
    b: { me: N_('Шестую открой'), re: N_('…Шестую. Записал. Ты гений.'), mood: 'surprised', out: 'big', row: N_('бизнес-идея') } },
  { id: 'taxi', who: 'taxi', emo: 'happy',
    say: N_('Это ты по встречке летел на Ленина? Я видел. Уважаю.'),
    a: { me: N_('Не я'), re: N_('Ну да. И я не я.'), mood: 'ok', out: '0' },
    b: { me: N_('Я'), re: N_('Псих. Держи, псих.'), mood: 'happy', out: 'big' } },
  { id: 'student', who: 'student', emo: 'sad',
    say: N_('Можно чаевые в следующей жизни? В этой — стипендия.'),
    a: { me: N_('Можно'), re: N_('Ты святой. Там — с меня две.'), mood: 'happy', out: 'none', row: N_('чаевые — в следующей жизни') },
    b: { me: N_('Нельзя'), re: N_('Ладно. Последние.'), mood: 'sad', out: 'tip' } },
  { id: 'alien', who: 'alien', emo: 'ok',
    say: N_('Мы прилетели за пиццей. Остальное у вас — так себе.'),
    a: { me: N_('Согласен'), re: N_('Тебя заберём последним.'), mood: 'happy', out: 'tip' },
    b: { me: N_('Обидно'), re: N_('Тебя заберём первым.'), mood: 'ok', out: '0', slam: true } },
  { id: 'alienboss', who: 'alien', emo: 'surprised',
    say: N_('Землянин. Отведи меня к своему начальнику.'),
    a: { me: N_('К Толику?'), re: N_('…Нет. Мы передумали. Летим домой.'), mood: 'scared', out: '0' },
    b: { me: N_('Сначала чаевые'), re: N_('Ваши обычаи странны. Держи.'), mood: 'surprised', out: 'big' } },

  /* ── добрые ── */
  { id: 'kind', who: 'kind_auntie', emo: 'happy',
    say: N_('Ты весь мокрый! На полотенце. И пирожок. И деньги.'),
    a: { me: N_('Спасибо'), re: N_('Тебе спасибо! Ты наш герой!'), mood: 'happy', out: 'tip' },
    b: { me: N_('Не надо'), re: N_('Надо! Бери, кому сказала!'), mood: 'happy', out: 'big' } },
  { id: 'dad', who: 'happy_dad', emo: 'happy',
    say: N_('Курьер! Ты сделал нам вечер! Серьёзно!'),
    a: { me: N_('Пожалуйста'), re: N_('Пять звёзд! Шесть! Семь!'), mood: 'happy', out: 'tip' },
    b: { me: N_('Это пицца'), re: N_('Нет, это ТЫ! Держи!'), mood: 'happy', out: 'big' } },
];

/* бонус «поддержать»: что клиент добавляет (doorstep.js bonus) */
export const BONUS = {
  find: N_('Кстати! Тут одна штука лежит: {what}. Это {where}, метров {m} отсюда. Глянь на карте!'),
  zhenya: N_('Скажи Дяде Жене, что ты от меня, — скинет {n} % на ремонт.'),
};
